version: '3'

services:

  broker-service:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports:
      - "8080:8081"
    deploy:
      mode: replicated
      replicas: 1